client:
  serverHost: localhost
  serverPort: 8964
  password: 123456
  proxies:
#    - host: localhost
#      port: 4456
#      protocol: tcp
#      openPort: 8890
    - host: localhost
      port: 9011
      protocol: tcp
      openPort: 8891
