// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_cmd_type.proto

// Protobuf Java Version: 3.25.3
package me.pgthinker.admin.enums;

public final class AdminCmdTypeProto {
  private AdminCmdTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 传输数据的指令类型
   * </pre>
   *
   * Protobuf enum {@code me.pgthinker.admin.CmdType}
   */
  public enum CmdType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *&#47;// 通用
     * </pre>
     *
     * <code>REGISTER = 0;</code>
     */
    REGISTER(0),
    /**
     * <pre>
     * 数据传输
     * </pre>
     *
     * <code>TRANSFER = 1;</code>
     */
    TRANSFER(1),
    /**
     * <pre>
     * 断开连接
     * </pre>
     *
     * <code>DISCONNECT = 2;</code>
     */
    DISCONNECT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *&#47;// 通用
     * </pre>
     *
     * <code>REGISTER = 0;</code>
     */
    public static final int REGISTER_VALUE = 0;
    /**
     * <pre>
     * 数据传输
     * </pre>
     *
     * <code>TRANSFER = 1;</code>
     */
    public static final int TRANSFER_VALUE = 1;
    /**
     * <pre>
     * 断开连接
     * </pre>
     *
     * <code>DISCONNECT = 2;</code>
     */
    public static final int DISCONNECT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static CmdType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CmdType forNumber(int value) {
      switch (value) {
        case 0: return REGISTER;
        case 1: return TRANSFER;
        case 2: return DISCONNECT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CmdType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdType>() {
            public CmdType findValueByNumber(int number) {
              return CmdType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdminCmdTypeProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final CmdType[] VALUES = values();

    public static CmdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CmdType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:me.pgthinker.admin.CmdType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024admin_cmd_type.proto\022\022me.pgthinker.adm" +
      "in*5\n\007CmdType\022\014\n\010REGISTER\020\000\022\014\n\010TRANSFER\020" +
      "\001\022\016\n\nDISCONNECT\020\002B/\n\030me.pgthinker.admin." +
      "enumsB\021AdminCmdTypeProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
