// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_transfer_message.proto

// Protobuf Java Version: 3.25.3
package me.pgthinker.admin.message;

public final class AdminTransferDataMessageProto {
  private AdminTransferDataMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransferDataMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.pgthinker.admin.TransferDataMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.me.pgthinker.admin.CmdType cmdType = 1;</code>
     * @return The enum numeric value on the wire for cmdType.
     */
    int getCmdTypeValue();
    /**
     * <code>.me.pgthinker.admin.CmdType cmdType = 1;</code>
     * @return The cmdType.
     */
    me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType getCmdType();

    /**
     * <code>.me.pgthinker.admin.AdminData data = 2;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.me.pgthinker.admin.AdminData data = 2;</code>
     * @return The data.
     */
    me.pgthinker.admin.message.AdminDataProto.AdminData getData();
    /**
     * <code>.me.pgthinker.admin.AdminData data = 2;</code>
     */
    me.pgthinker.admin.message.AdminDataProto.AdminDataOrBuilder getDataOrBuilder();
  }
  /**
   * <pre>
   * 传输数据的消息定义
   * </pre>
   *
   * Protobuf type {@code me.pgthinker.admin.TransferDataMessage}
   */
  public static final class TransferDataMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.pgthinker.admin.TransferDataMessage)
      TransferDataMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransferDataMessage.newBuilder() to construct.
    private TransferDataMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransferDataMessage() {
      cmdType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransferDataMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.pgthinker.admin.message.AdminTransferDataMessageProto.internal_static_me_pgthinker_admin_TransferDataMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.pgthinker.admin.message.AdminTransferDataMessageProto.internal_static_me_pgthinker_admin_TransferDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage.class, me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage.Builder.class);
    }

    private int bitField0_;
    public static final int CMDTYPE_FIELD_NUMBER = 1;
    private int cmdType_ = 0;
    /**
     * <code>.me.pgthinker.admin.CmdType cmdType = 1;</code>
     * @return The enum numeric value on the wire for cmdType.
     */
    @java.lang.Override public int getCmdTypeValue() {
      return cmdType_;
    }
    /**
     * <code>.me.pgthinker.admin.CmdType cmdType = 1;</code>
     * @return The cmdType.
     */
    @java.lang.Override public me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType getCmdType() {
      me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType result = me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType.forNumber(cmdType_);
      return result == null ? me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private me.pgthinker.admin.message.AdminDataProto.AdminData data_;
    /**
     * <code>.me.pgthinker.admin.AdminData data = 2;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.me.pgthinker.admin.AdminData data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public me.pgthinker.admin.message.AdminDataProto.AdminData getData() {
      return data_ == null ? me.pgthinker.admin.message.AdminDataProto.AdminData.getDefaultInstance() : data_;
    }
    /**
     * <code>.me.pgthinker.admin.AdminData data = 2;</code>
     */
    @java.lang.Override
    public me.pgthinker.admin.message.AdminDataProto.AdminDataOrBuilder getDataOrBuilder() {
      return data_ == null ? me.pgthinker.admin.message.AdminDataProto.AdminData.getDefaultInstance() : data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdType_ != me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType.REGISTER.getNumber()) {
        output.writeEnum(1, cmdType_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getData());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdType_ != me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType.REGISTER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmdType_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage)) {
        return super.equals(obj);
      }
      me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage other = (me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage) obj;

      if (cmdType_ != other.cmdType_) return false;
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + cmdType_;
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 传输数据的消息定义
     * </pre>
     *
     * Protobuf type {@code me.pgthinker.admin.TransferDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.pgthinker.admin.TransferDataMessage)
        me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.pgthinker.admin.message.AdminTransferDataMessageProto.internal_static_me_pgthinker_admin_TransferDataMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.pgthinker.admin.message.AdminTransferDataMessageProto.internal_static_me_pgthinker_admin_TransferDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage.class, me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage.Builder.class);
      }

      // Construct using me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cmdType_ = 0;
        data_ = null;
        if (dataBuilder_ != null) {
          dataBuilder_.dispose();
          dataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.pgthinker.admin.message.AdminTransferDataMessageProto.internal_static_me_pgthinker_admin_TransferDataMessage_descriptor;
      }

      @java.lang.Override
      public me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage getDefaultInstanceForType() {
        return me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage.getDefaultInstance();
      }

      @java.lang.Override
      public me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage build() {
        me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage buildPartial() {
        me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage result = new me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmdType_ = cmdType_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.data_ = dataBuilder_ == null
              ? data_
              : dataBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage) {
          return mergeFrom((me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage other) {
        if (other == me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage.getDefaultInstance()) return this;
        if (other.cmdType_ != 0) {
          setCmdTypeValue(other.getCmdTypeValue());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cmdType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getDataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cmdType_ = 0;
      /**
       * <code>.me.pgthinker.admin.CmdType cmdType = 1;</code>
       * @return The enum numeric value on the wire for cmdType.
       */
      @java.lang.Override public int getCmdTypeValue() {
        return cmdType_;
      }
      /**
       * <code>.me.pgthinker.admin.CmdType cmdType = 1;</code>
       * @param value The enum numeric value on the wire for cmdType to set.
       * @return This builder for chaining.
       */
      public Builder setCmdTypeValue(int value) {
        cmdType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.me.pgthinker.admin.CmdType cmdType = 1;</code>
       * @return The cmdType.
       */
      @java.lang.Override
      public me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType getCmdType() {
        me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType result = me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType.forNumber(cmdType_);
        return result == null ? me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType.UNRECOGNIZED : result;
      }
      /**
       * <code>.me.pgthinker.admin.CmdType cmdType = 1;</code>
       * @param value The cmdType to set.
       * @return This builder for chaining.
       */
      public Builder setCmdType(me.pgthinker.admin.enums.AdminCmdTypeProto.CmdType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        cmdType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.me.pgthinker.admin.CmdType cmdType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmdType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdType_ = 0;
        onChanged();
        return this;
      }

      private me.pgthinker.admin.message.AdminDataProto.AdminData data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.pgthinker.admin.message.AdminDataProto.AdminData, me.pgthinker.admin.message.AdminDataProto.AdminData.Builder, me.pgthinker.admin.message.AdminDataProto.AdminDataOrBuilder> dataBuilder_;
      /**
       * <code>.me.pgthinker.admin.AdminData data = 2;</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.me.pgthinker.admin.AdminData data = 2;</code>
       * @return The data.
       */
      public me.pgthinker.admin.message.AdminDataProto.AdminData getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? me.pgthinker.admin.message.AdminDataProto.AdminData.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <code>.me.pgthinker.admin.AdminData data = 2;</code>
       */
      public Builder setData(me.pgthinker.admin.message.AdminDataProto.AdminData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
        } else {
          dataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.me.pgthinker.admin.AdminData data = 2;</code>
       */
      public Builder setData(
          me.pgthinker.admin.message.AdminDataProto.AdminData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.me.pgthinker.admin.AdminData data = 2;</code>
       */
      public Builder mergeData(me.pgthinker.admin.message.AdminDataProto.AdminData value) {
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            data_ != null &&
            data_ != me.pgthinker.admin.message.AdminDataProto.AdminData.getDefaultInstance()) {
            getDataBuilder().mergeFrom(value);
          } else {
            data_ = value;
          }
        } else {
          dataBuilder_.mergeFrom(value);
        }
        if (data_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.me.pgthinker.admin.AdminData data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = null;
        if (dataBuilder_ != null) {
          dataBuilder_.dispose();
          dataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.me.pgthinker.admin.AdminData data = 2;</code>
       */
      public me.pgthinker.admin.message.AdminDataProto.AdminData.Builder getDataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.me.pgthinker.admin.AdminData data = 2;</code>
       */
      public me.pgthinker.admin.message.AdminDataProto.AdminDataOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              me.pgthinker.admin.message.AdminDataProto.AdminData.getDefaultInstance() : data_;
        }
      }
      /**
       * <code>.me.pgthinker.admin.AdminData data = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.pgthinker.admin.message.AdminDataProto.AdminData, me.pgthinker.admin.message.AdminDataProto.AdminData.Builder, me.pgthinker.admin.message.AdminDataProto.AdminDataOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.pgthinker.admin.message.AdminDataProto.AdminData, me.pgthinker.admin.message.AdminDataProto.AdminData.Builder, me.pgthinker.admin.message.AdminDataProto.AdminDataOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.pgthinker.admin.TransferDataMessage)
    }

    // @@protoc_insertion_point(class_scope:me.pgthinker.admin.TransferDataMessage)
    private static final me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage();
    }

    public static me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransferDataMessage>
        PARSER = new com.google.protobuf.AbstractParser<TransferDataMessage>() {
      @java.lang.Override
      public TransferDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TransferDataMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransferDataMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.pgthinker.admin.message.AdminTransferDataMessageProto.TransferDataMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_pgthinker_admin_TransferDataMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_pgthinker_admin_TransferDataMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034admin_transfer_message.proto\022\022me.pgthi" +
      "nker.admin\032\024admin_cmd_type.proto\032\020admin_" +
      "data.proto\"p\n\023TransferDataMessage\022,\n\007cmd" +
      "Type\030\001 \001(\0162\033.me.pgthinker.admin.CmdType\022" +
      "+\n\004data\030\002 \001(\0132\035.me.pgthinker.admin.Admin" +
      "DataB=\n\032me.pgthinker.admin.messageB\035Admi" +
      "nTransferDataMessageProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          me.pgthinker.admin.enums.AdminCmdTypeProto.getDescriptor(),
          me.pgthinker.admin.message.AdminDataProto.getDescriptor(),
        });
    internal_static_me_pgthinker_admin_TransferDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_pgthinker_admin_TransferDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_pgthinker_admin_TransferDataMessage_descriptor,
        new java.lang.String[] { "CmdType", "Data", });
    me.pgthinker.admin.enums.AdminCmdTypeProto.getDescriptor();
    me.pgthinker.admin.message.AdminDataProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
